### ISSUE TITLE
Time Role [seems to 'loop']

### ISSUE THREAD

**Issue by Sashasonic** [bobloy/Fox-V3#128]
Have been meaning to ask if TimeRole could be changed to **not 'loop'**, ie: for when the timerole is activated, '**onjoin', only or a toggle, and not when it's removed for whatever reason**. As it's then re-applied at the moment, no matter how long the person has been in the server.

TIA.

**Comment by bobloy** [comment]
I'm not sure what you're asking here. Could you clarify?

Timerole checks how long the member has been on the server and compares it to the set days and hours. 
Leaving and rejoining the server would reset a users "joined_at" date

Timerole runs every hour; running based on when a user joins is not the best use of this cog. This usually meant for longer term times. 
If you're trying to add a role to everyone that's been on the server exactly an hour, that's more precise that this cog is designed for.

**Comment by Sashasonic** [comment]
Hi, sorry, thought I had been pretty clear e: for when the timerole is activated, 'onjoin', **only or a toggle**, and not when it's removed for whatever reason. 

At the moment: **it's then re-applied when I remove the timedrole**, no matter how long the person has been in the server.

**Comment by bobloy** [comment]
Ah, I understand. This would check if they've already received the role before, and skip them if so.

This could be a fine addition, I'll look into it.

**Comment by Sashasonic** [comment]
Thank you, sounds good.. 👍
