### ISSUE TITLE
[AudioTrivia] Games list not working at all.

### ISSUE THREAD

**Issue by WhynautTV** [bobloy/Fox-V3#141]
The anime list for audio trivia works most of the time with the occasional, no sound, completely stops working. The "games" list/category does not play any sound at all and never skips or continues. Tried on a completely fresh redbot install and same issue. No log errors.

**Comment by bobloy** [comment]
Looks like the youtube account with the videos on that list was terminated. I'll look into updating the list with new links.

**Comment by bobloy** [comment]
Updating the game list with new links is a lot of work unfortunately. I've fixed a couple but will not be able to get them all fixed soon. Any PRs to provide accurate links would be appreciated.

**Comment by WhynautTV** [comment]
Ouch. That explains a lot. Thanks for looking into it, didn't even think to check if the links worked.

**Comment by bobloy** [comment]
Addressed in #146 for now
