### ISSUE TITLE
Howdoi issue

### ISSUE THREAD

**Issue by doodthedoodthedood** [bobloy/Fox-V3#17]
I installed howdoi, then when I loaded it, I got this message:
` File "C:\Users\username\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\howdoi\__init__.py", line 1, in <module>
    from .howdoi import Howdoi
  File "C:\Users\username\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\howdoi\howdoi.py", line 5, in <module>
    from .utils.chat_formatting import pagify
ModuleNotFoundError: No module named 'howdoi.utils'`

**Comment by bobloy** [comment]
Howdoi is currently an **Incomplete** cog unfortunately. You can check the status of each of the cogs on the status page [here](https://github.com/bobloy/Fox-V3#fox-v3)
