### ISSUE TITLE
IsItDown always gives Down

### ISSUE THREAD

**Issue by DrTipmack** [bobloy/Fox-V3#171]
**Describe the bug**
There is no way to get anything other than down
**To Reproduce**

1. Load cog 'isitdown'
2. Run command 'isitdown www.google.com'
3. See error

**Expected behavior**
To give the real status of online websites

**Screenshots or Error Messages**
![image](https://user-images.githubusercontent.com/57598077/109564691-548dc080-7ad9-11eb-8377-4746fabbda45.png)

**Additional context**
I am using a lot of other cogs, so maybe that might be something to consider

**Comment by bobloy** [comment]
Latest patch fixed this, thanks for the report.
