### ISSUE TITLE
fifo cron looses an hour in the middle of the schedule

### ISSUE THREAD

**Issue by jjffnn** [bobloy/Fox-V3#176]
**Describe the bug**
The cronjob runs a day off, i set it for tuesday and thursday but it runs wednesday and friday.
But worse is that it will run a the designated time but then lose an hour after a couple of runs (See checktask schedule below)

**To Reproduce**
Simply setting a cronjob up

**Expected behavior**
Running the job as designated time each time

**Screenshots or Error Messages**
![image](https://user-images.githubusercontent.com/13290079/112297423-2c3b5100-8c96-11eb-9205-572c3694a3b3.png)

**Additional context**
I am running it on a RPi4.
I have two crons set up and both of them lose an hour somewhere within the next 10 triggers according the the schedule.

**Comment by bobloy** [comment]
The hour off is not a bug. CET experiences daylight savings on March 28th.

The days beings off is likely because the first day of the week doesnt match cron guru. I will see about fixing that issue.

**Comment by jjffnn** [comment]
Boy do i feel silly now. I've stared at the issue so long i stopped thinking logically. Thank you for the quick response.
The off day can easily be fixed by offsetting it so instead of 2,4 i'll just use 1,3.
Thanks again and sorry for wasting your time. :)
