### ISSUE TITLE
[Audiotrivia] Playing status should be hidden

### ISSUE THREAD

**Issue by pabloleban** [bobloy/Fox-V3#24]
Not a breaking bug, but anyone who plays audiotrivia should put `[p]audioset status` to disable the song name displayed in the bot status to avoid players cheating.

**Comment by bobloy** [comment]
Latest commit https://github.com/bobloy/Fox-V3/commit/7fc081de8706e905d98c6c14e2827d44a0f70a3f has added a warning for this setting, but does not automatically disable it. Maybe it will do that in future releases.
