### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [bobloy/Fox-V3#29]
After updating red planttycoon lo longer works giving the error code: 

RuntimeError: The PlantTycoon cog in the planttycoon.planttycoon package does not inherit from the commands.Cog bas
e class. The cog author must update the cog to adhere to this requirement.

**Comment by bobloy** [comment]
Be sure your cog is the latest version. Unload the cog before updating it, then reload it.

If that doesn't work, try uninstalling and reinstalling the cog.
