### ISSUE TITLE
lseen - not working properly on RED v3.1

### ISSUE THREAD

**Issue by Skyrid3r** [bobloy/Fox-V3#59]
Haven't seen it being reported yet, but apparently lseen isn't working on RED v3.1 properly. It works when those are online, but for those who were online and then offline, lseen them will show up as never seen this user:

![image](https://user-images.githubusercontent.com/6794064/60873273-681a5280-a236-11e9-9ff7-ea76117859b3.png)

**Comment by Ianardo-DiCaprio** [comment]
This is now fixed and the issue can be closed.
