### ISSUE TITLE
Timerole not adding roles

### ISSUE THREAD

**Issue by callumcosta2402** [bobloy/Fox-V3#66]
I seem to have set everything up properly and everything's up to date however its not applying any roles.

**Comment by Ianardo-DiCaprio** [comment]
Issue should be fixed.

**Comment by Peechaya** [comment]
I have the same issue, it always says "These members have received the following roles: <member> (Failed)"

**Comment by Ianardo-DiCaprio** [comment]
That only shows when the bot has insufficient permissions.

**Comment by Peechaya** [comment]
Bot is Administrator. What else can it be?

**Comment by callumcosta2402** [comment]
> Bot is Administrator. What else can it be?
> 
> Edit: Ohh nevermind! I just realized that the role was below the roles that should be assigned. That must be the problem!

For the sake of ease I usually put the bots role at the top of the list. it especially helps when using things like stream roles as it will cover every role.
