### ISSUE TITLE
Issue with QR Invite

### ISSUE THREAD

**Issue by pyhuee** [bobloy/Fox-V3#88]
![image](https://user-images.githubusercontent.com/62118708/83803286-4ad64a00-a67a-11ea-85cc-09f0984f286d.png)
 I know its in beta, the bot said in the discord server
![image](https://user-images.githubusercontent.com/62118708/83803430-87a24100-a67a-11ea-8ea3-1a4315f87d3e.png)
 Thank you

**Comment by bobloy** [comment]
This should now be fixed.
