### ISSUE TITLE
Chatter Error when using Redbot 3.3.9.

### ISSUE THREAD

**Issue by SilentBlade1472** [bobloy/Fox-V3#91]
I am running Redbot 3.3.9 and Discord.py 1.3.3 and my python version is 3.8.3.
Whenever I try running chatter I get the error 
 
  time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

Which from what I read is because the time it was written it used the depreciated clock() function,

**Comment by AlastorStrixEfuartus** [comment]
same problem here im using RED 3.3.10 - python 3.8.5 - discord.py 1.3.4
